### ISSUE TITLE
Question: Low volume  with this preset?

### ISSUE THREAD

**Issue by GITMichaelK** [sebastian-de/easyeffects-thinkpad-unsuck#2]
Thanks a lot for your effort and the promising preset.
I justed switched my LENOVO T14s Gen. 1 under MANJARO to PipeWire and installed EasyEffects with some Preset-packages, as the original sound under MANJARO is terrible. Strange for me: Running WINDOWS under MANAJRO and VirtualBox, the same .mp3-File sounds OK.

Now I tried with EasyEffects and could improve the quality with different presets:
```
$ easyeffects --presets
Ausgabe-Voreinstellungen: 
Advanced Auto Gain,
Bass Boosted,
Bass Enhancing + Perfect EQ,
Boosted,
MakeSoundGreat,
Loudness+Autogain,
Perfect EQ,
PipeWire EasyEffects Default,
laptop_unsuck,
Eingabe-Voreinstellungen: 
```
My Problem: The volume running laptop_unsuck is much lower in comparison to the other presets. Typically I have 30% volume but I need about 90% to achieve a similar level with laptop_unsuck. How can I solve this? Do you have a recommendation, how to decide between the presets or is there a tutorial for further improvement?
Thank you!

**Comment by spikespaz** [comment]
Go adjust the sliders and numbers in the preset stages if some of the frequencies are too quiet for you.

I don't know much about audio but I do understand that for an equalizer, you raise and lower a multiplier (volume) for various frequencies and somehow interpolate those adjustment points with a wave function.

While this is not an equalizer, it does do something similar (it is a superset of an equalizer). For the audio to sound "balanced", certain frequencies had to be lowered (made quieter) to make others more prominent. The quietness is expected.

**Comment by GITMichaelK** [comment]
Thanks a lot for your reply:
> Go adjust the sliders and numbers in the preset stages if some of the frequencies are too quiet for you.

But my issue is different:
- PipeWire is installed, EasyEffects is running, the volume for my system is set to 30%, I'm playing a MP3-File.
- I switch to preset `Advanced Auto Gain`: I can hear the sound
- I switch to preset `Bass Boosted`: I can hear the sound a bit more bass boosted, but almost with similar volume.
- I switch to preset `laptop_unsuck`: I hear nothing at all, only after setting the speakers volume to 90% I can hear it, but very quiet!

How to solve this?

**Comment by sebastian-de** [comment]
It's possible that the T14s Gen1 has different speakers than the Gen2. In this case it's likely that the preset in this repository will make the sound worse instead of improving it.

I'm not an audio expert either, but as @spikespaz already said, a decrease in overall volume is expected if you want to boost the lower frequencies (but not as strong as you describe).

If you want to get the best result for the speakers of your model, I recommend to follow the guide mentioned in the readme (in EasyEffects hit `F1` for help and select _Enhancing your internal notebook speakers without using an Equalizer_).

**Comment by sebastian-de** [comment]
> * I switch to preset `laptop_unsuck`

Maybe you are using the old version from the gist instead of the current version from this repository? It looks like it since the preset file is now named `thinkpad_unsuck`.
This might explain the very low volume, since the parameters for the filter plugin changed in EasyEffects 7.08: https://github.com/wwmm/easyeffects/blob/master/CHANGELOG.md#708

Please make sure you are using the latest preset version, the filter mode should be `RLC (BT)`:
https://github.com/sebastian-de/easyeffects-thinkpad-unsuck/blob/6356f4953b54911e156f31ed90da29eb4436ad7e/thinkpad-unsuck.json#L21

**Comment by GITMichaelK** [comment]
Great, you made it:
> Maybe you are using the old version

I had this one:
[laptop_unsuck.json](https://github.com/sebastian-de/easyeffects-thinkpad-unsuck/files/13770554/laptop_unsuck.json)
Using the following, it's OK:
[laptop_unsuckNEU.json](https://github.com/sebastian-de/easyeffects-thinkpad-unsuck/files/13770555/laptop_unsuckNEU.json)

Thanks a lot!

**Comment by sebastian-de** [comment]
Great, you're welcome!

**Comment by spikespaz** [comment]
What is this NEU file?
`https://github.com/sebastian-de/easyeffects-thinkpad-unsuck/files/13770555/laptop_unsuckNEU.json`

**Comment by GITMichaelK** [comment]
It's [this one](https://github.com/sebastian-de/easyeffects-thinkpad-unsuck/blob/6356f4953b54911e156f31ed90da29eb4436ad7e/thinkpad-unsuck.json#L21) works fine.
The URL for the one, that doesn't work for me can be found [here](https://github.com/sebastian-de/easyeffects-thinkpad-unsuck/issues/2#issuecomment-1869416767). AS JSON does typically not allow comments, may be the revision-ID could be part of the filename in future?

**Comment by sebastian-de** [comment]
> AS JSON does typically not allow comments, may be the revision-ID could be part of the filename in future?

Well, one of the advantages of git is that you don't have to do these kind of things.

I manage all my dotfiles using git (this repository just contains a copy of a single preset I use).

But you can just use curl to get the latest version:

```
curl 'https://raw.githubusercontent.com/sebastian-de/easyeffects-thinkpad-unsuck/main/thinkpad-unsuck.json' > ~/.config/easyeffects/output/thinkpad_unsuck.json
```
